language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit --coverage-clover clover
  - composer validate

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php

matrix:
  allow_failures:
    - php: hhvm
